# Created using wingetcreate

PackageIdentifier: ExpressVPN.ExpressVPN
PackageVersion: 10.2.4.11
PackageLocale: en-US
Publisher: ExpressVPN
PackageName: ExpressVPN
License: Copyright (c) ExpressVPN. All rights reserved.
ShortDescription: ExpressVPN
ManifestType: defaultLocale
ManifestVersion: 1.0.0
