id: 
name: GitOps.PullRequestIssueManagement
description: GitOps.PullRequestIssueManagement primitive
owner: 
resource: repository
disabled: false
where: 
configuration:
  resourceManagementConfiguration:
    scheduledSearches:
    - description: 
      frequencies:
      - hourly:
          hour: 6
      filters:
      - isIssue
      - isOpen
      - hasLabel:
          label: Needs-Author-Feedback
      - hasLabel:
          label: No-Recent-Activity
      - noActivitySince:
          days: 7
      - isNotLabeledWith:
          label: Issue-Feature
      - isNotLabeledWith:
          label: Issue-Bug
      actions:
      - closeIssue
    - description: 
      frequencies:
      - hourly:
          hour: 3
      filters:
      - isIssue
      - isOpen
      - hasLabel:
          label: Needs-Author-Feedback
      - noActivitySince:
          days: 7
      - isNotLabeledWith:
          label: No-Recent-Activity
      actions:
      - addLabel:
          label: No-Recent-Activity
      - addReply:
          reply: This issue has been automatically marked as stale because it has been marked as requiring author feedback but has not had any activity for **7 days**. It will be closed if no further activity occurs **within 7 days of this comment**.
    - description: 
      frequencies:
      - hourly:
          hour: 3
      filters:
      - isIssue
      - isOpen
      - hasLabel:
          label: Resolution-Duplicate
      - noActivitySince:
          days: 1
      actions:
      - addReply:
          reply: This issue has been marked as duplicate and has not had any activity for **1 day**. It will be closed for housekeeping purposes.
      - removeLabel:
          label: Needs-Triage
      - closeIssue
    - description: 
      frequencies:
      - hourly:
          hour: 3
      filters:
      - isPullRequest
      - isOpen
      - hasLabel:
          label: Needs-Author-Feedback
      - hasLabel:
          label: No-Recent-Activity
      - noActivitySince:
          days: 7
      actions:
      - closeIssue
    - description: 
      frequencies:
      - hourly:
          hour: 6
      filters:
      - isPullRequest
      - isOpen
      - hasLabel:
          label: Needs-Author-Feedback
      - noActivitySince:
          days: 7
      - isNotLabeledWith:
          label: No-Recent-Activity
      actions:
      - addLabel:
          label: No-Recent-Activity
      - addReply:
          reply: This pull request has been automatically marked as stale because it has been marked as requiring author feedback but has not had any activity for **7 days**. It will be closed if no further activity occurs **within 7 days of this comment**.
    eventResponderTasks:
    - if:
      - payloadType: Issues
      - or:
        - and:
          - isAction:
              action: Opened
      then:
      - addLabel:
          label: Needs-Triage
      description: 
    - if:
      - payloadType: Issue_Comment
      - isAction:
          action: Created
      - isActivitySender:
          issueAuthor: True
      - hasLabel:
          label: Needs-Author-Feedback
      then:
      - addLabel:
          label: Needs-Attention
      - removeLabel:
          label: Needs-Author-Feedback
      - removeLabel:
          label: No-Recent-Activity
      description: 
    - if:
      - payloadType: Issues
      - not:
          isAction:
            action: Closed
      - hasLabel:
          label: No-Recent-Activity
      then:
      - removeLabel:
          label: No-Recent-Activity
      description: 
    - if:
      - payloadType: Issue_Comment
      - hasLabel:
          label: No-Recent-Activity
      then:
      - removeLabel:
          label: No-Recent-Activity
      description: 
    - if:
      - payloadType: Pull_Request
      - isAction:
          action: Opened
      then:
      - addCodeFlowLink
      description: 
    - if:
      - payloadType: Pull_Request_Review
      - isAction:
          action: Submitted
      - isReviewState:
          reviewState: Changes_requested
      then:
      - addLabel:
          label: Needs-Author-Feedback
      description: 
    - if:
      - payloadType: Pull_Request
      - isActivitySender:
          issueAuthor: True
      - not:
          isAction:
            action: Closed
      - hasLabel:
          label: Needs-Author-Feedback
      then:
      - removeLabel:
          label: Needs-Author-Feedback
      description: 
    - if:
      - payloadType: Issue_Comment
      - isActivitySender:
          issueAuthor: True
      - hasLabel:
          label: Needs-Author-Feedback
      then:
      - removeLabel:
          label: Needs-Author-Feedback
      description: 
    - if:
      - payloadType: Pull_Request_Review
      - isActivitySender:
          issueAuthor: True
      - hasLabel:
          label: Needs-Author-Feedback
      then:
      - removeLabel:
          label: Needs-Author-Feedback
      description: 
    - if:
      - payloadType: Pull_Request
      - not:
          isAction:
            action: Closed
      - hasLabel:
          label: No-Recent-Activity
      then:
      - removeLabel:
          label: No-Recent-Activity
      description: 
    - if:
      - payloadType: Issue_Comment
      - hasLabel:
          label: No-Recent-Activity
      then:
      - removeLabel:
          label: No-Recent-Activity
      description: 
    - if:
      - payloadType: Pull_Request_Review
      - hasLabel:
          label: No-Recent-Activity
      then:
      - removeLabel:
          label: No-Recent-Activity
      description: 
    - if:
      - payloadType: Pull_Request
      - hasLabel:
          label: AutoMerge
      then:
      - enableAutoMerge:
          mergeMethod: Squash
      description: 
    - if:
      - payloadType: Pull_Request
      - labelRemoved:
          label: AutoMerge
      then:
      - disableAutoMerge
      description: 
    - if:
      - payloadType: Pull_Request
      then:
      - inPrLabel:
          label: In-PR
      description: 
    - if:
      - payloadType: Issues
      - or:
        - isAction:
            action: Opened
        - isAction:
            action: Reopened
      - or:
        - not:
            bodyContains:
              pattern: .+
              isRegex: True
      then:
      - closeIssue
      - addLabel:
          label: Needs-Author-Feedback
      - addReply:
          reply: "Hi! Thanks for attempting to open an issue. Unfortunately, you didn't write anything in the body which makes it impossible to understand your concern. You are welcome to fix up the issue and try again by opening another issue with the body filled out. "
      description: 
    - if:
      - payloadType: Issues
      - hasLabel:
          label: In-PR
      - hasLabel:
          label: Help-Wanted
      - isLabeled
      then:
      - removeLabel:
          label: Help-Wanted
      description: 
    - if:
      - payloadType: Issue_Comment
      - commentContains:
          pattern: Duplicate\s+of\s+\#?\s*\d+
          isRegex: True
      - or:
        - activitySenderHasPermission:
            permission: Admin
        - activitySenderHasPermission:
            permission: Write
      then:
      - addReply:
          reply: "Hi! We've identified this issue as a duplicate of another one that already exists on this Issue Tracker. This specific instance is being closed in favor of tracking the concern over on the referenced thread. Be sure to add your \U0001F44D to that issue. Thanks for your report!"
      - closeIssue
      - removeLabel:
          label: Needs-Triage
      - addLabel:
          label: Resolution-Duplicate
      - removeLabel:
          label: Needs-Author-Feedback
      description: 
    - if:
      - payloadType: Issue_Comment
      - commentContains:
          pattern: '\/feedback'
          isRegex: True
      - or:
        - activitySenderHasPermission:
            permission: Admin
        - activitySenderHasPermission:
            permission: Write
      then:
      - addReply:
          reply: Hi there!<br><br>Can you please send us feedback with the Feedback Hub with this issue and paste the link here so we can more easily find your crash information on the back end?<br><br>Thanks!<br><br>![image](https://user-images.githubusercontent.com/18221333/62478757-b69d0d00-b760-11e9-9626-1fa33c91e7c5.png) ![image](https://user-images.githubusercontent.com/18221333/62478649-6de55400-b760-11e9-806e-5aab7e085a9f.png)
      - addLabel:
          label: Needs-Author-Feedback
      description: 
    - if:
      - payloadType: Issue_Comment
      then:
      - cleanEmailReply
      description: 
    - if:
      - payloadType: Pull_Request
      then:
      - labelSync:
          pattern: Issue-
      - labelSync:
          pattern: Area-
      - labelSync:
          pattern: Priority-
      - labelSync:
          pattern: Product-
      - labelSync:
          pattern: Severity-
      - labelSync:
          pattern: Impact-
      description: 
onFailure: 
onSuccess: 
