trigger:
- none

pool:
  vmImage: 'windows-latest'

steps:
- task: Semmle@1
  inputs:
    sourceCodeDirectory: '$(Build.SourcesDirectory)/src'
    language: 'csharp'
    querySuite: 'Recommended'
    timeout: '1800'
    addProjectDirToScanningExclusionList: true
  continueOnError: true

- task: CredScan@2
  inputs:
    scanFolder: '$(Build.SourcesDirectory)'
    debugMode: false
  continueOnError: true
