# Created using wingetcreate 1.2.7.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.4.0.schema.json

PackageIdentifier: Microsoft.DevHome
PackageVersion: 2.0
Platform:
- Windows.Desktop
MinimumOSVersion: 10.0.22000.0
Dependencies:
  PackageDependencies:
  - PackageIdentifier: Microsoft.WindowsAppRuntime.1.3
PackageFamilyName: Microsoft.Windows.DevHome_8wekyb3d8bbwe
Installers:
- Platform:
  - Windows.Desktop
  MinimumOSVersion: 10.0.22000.0
  Architecture: x86
  InstallerType: msix
  InstallerUrl: https://github.com/microsoft/devhome/releases/download/v0.200.170.0/Windows.DevHome_0.200.170.0.msixbundle
  InstallerSha256: AF957CE1B85FBB1F6D2B70D58E6E92314C52AAB40AEE427B49BB8AECA0625AA6
  SignatureSha256: E29BD2FDA9EE8EC1A822753590E7BC35181A1FDC145BB49F86E94CACB9BC45BE
  PackageFamilyName: Microsoft.Windows.DevHome_8wekyb3d8bbwe
- Platform:
  - Windows.Desktop
  MinimumOSVersion: 10.0.22000.0
  Architecture: x64
  InstallerType: msix
  InstallerUrl: https://github.com/microsoft/devhome/releases/download/v0.200.170.0/Windows.DevHome_0.200.170.0.msixbundle
  InstallerSha256: AF957CE1B85FBB1F6D2B70D58E6E92314C52AAB40AEE427B49BB8AECA0625AA6
  SignatureSha256: E29BD2FDA9EE8EC1A822753590E7BC35181A1FDC145BB49F86E94CACB9BC45BE
  PackageFamilyName: Microsoft.Windows.DevHome_8wekyb3d8bbwe
- Platform:
  - Windows.Desktop
  MinimumOSVersion: 10.0.22000.0
  Architecture: arm64
  InstallerType: msix
  InstallerUrl: https://github.com/microsoft/devhome/releases/download/v0.200.170.0/Windows.DevHome_0.200.170.0.msixbundle
  InstallerSha256: AF957CE1B85FBB1F6D2B70D58E6E92314C52AAB40AEE427B49BB8AECA0625AA6
  SignatureSha256: E29BD2FDA9EE8EC1A822753590E7BC35181A1FDC145BB49F86E94CACB9BC45BE
  PackageFamilyName: Microsoft.Windows.DevHome_8wekyb3d8bbwe
ManifestType: installer
ManifestVersion: 1.4.0
