# Created using wingetcreate 0.2.0.29
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.0.0.schema.json

PackageIdentifier: SpotifyLtd.Spotify
PackageVersion: 0.1.2.3
PackageLocale: en-US
Publisher: Spotify Ltd
PackageName: Spotify
License: Copyright (c) 2021, Spotify Ltd
ShortDescription: SpotifyInstaller
ManifestType: defaultLocale
ManifestVersion: 1.0.0

